# indian_stocks.py
"""
Indian Stock Universe Configuration
Curated list of major liquid Indian stocks for data collection

Total Stocks: 100 (most liquid NSE F&O stocks)
"""

INDIAN_STOCKS = {
    'RELIANCE': {'name': 'Reliance Industries Ltd', 'exchange': 'NSE', 'yahoo': 'RELIANCE.NS', 'nse': 'RELIANCE', 'sector': 'Energy'},
    'TCS': {'name': 'Tata Consultancy Services Ltd', 'exchange': 'NSE', 'yahoo': 'TCS.NS', 'nse': 'TCS', 'sector': 'IT'},
    'HDFCBANK': {'name': 'HDFC Bank Ltd', 'exchange': 'NSE', 'yahoo': 'HDFCBANK.NS', 'nse': 'HDFCBANK', 'sector': 'Finance'},
    'INFY': {'name': 'Infosys Ltd', 'exchange': 'NSE', 'yahoo': 'INFY.NS', 'nse': 'INFY', 'sector': 'IT'},
    'ICICIBANK': {'name': 'ICICI Bank Ltd', 'exchange': 'NSE', 'yahoo': 'ICICIBANK.NS', 'nse': 'ICICIBANK', 'sector': 'Finance'},
    'HINDUNILVR': {'name': 'Hindustan Unilever Ltd', 'exchange': 'NSE', 'yahoo': 'HINDUNILVR.NS', 'nse': 'HINDUNILVR', 'sector': 'FMCG'},
    'ITC': {'name': 'ITC Ltd', 'exchange': 'NSE', 'yahoo': 'ITC.NS', 'nse': 'ITC', 'sector': 'FMCG'},
    'SBIN': {'name': 'State Bank of India', 'exchange': 'NSE', 'yahoo': 'SBIN.NS', 'nse': 'SBIN', 'sector': 'Finance'},
    'BHARTIARTL': {'name': 'Bharti Airtel Ltd', 'exchange': 'NSE', 'yahoo': 'BHARTIARTL.NS', 'nse': 'BHARTIARTL', 'sector': 'Telecom'},
    'KOTAKBANK': {'name': 'Kotak Mahindra Bank Ltd', 'exchange': 'NSE', 'yahoo': 'KOTAKBANK.NS', 'nse': 'KOTAKBANK', 'sector': 'Finance'},
    'LT': {'name': 'Larsen & Toubro Ltd', 'exchange': 'NSE', 'yahoo': 'LT.NS', 'nse': 'LT', 'sector': 'Infrastructure'},
    'AXISBANK': {'name': 'Axis Bank Ltd', 'exchange': 'NSE', 'yahoo': 'AXISBANK.NS', 'nse': 'AXISBANK', 'sector': 'Finance'},
    'ASIANPAINT': {'name': 'Asian Paints Ltd', 'exchange': 'NSE', 'yahoo': 'ASIANPAINT.NS', 'nse': 'ASIANPAINT', 'sector': 'Consumer'},
    'MARUTI': {'name': 'Maruti Suzuki India Ltd', 'exchange': 'NSE', 'yahoo': 'MARUTI.NS', 'nse': 'MARUTI', 'sector': 'Auto'},
    'TITAN': {'name': 'Titan Company Ltd', 'exchange': 'NSE', 'yahoo': 'TITAN.NS', 'nse': 'TITAN', 'sector': 'Consumer'},
    'SUNPHARMA': {'name': 'Sun Pharmaceutical Industries Ltd', 'exchange': 'NSE', 'yahoo': 'SUNPHARMA.NS', 'nse': 'SUNPHARMA', 'sector': 'Pharma'},
    'ULTRACEMCO': {'name': 'UltraTech Cement Ltd', 'exchange': 'NSE', 'yahoo': 'ULTRACEMCO.NS', 'nse': 'ULTRACEMCO', 'sector': 'Cement'},
    'BAJFINANCE': {'name': 'Bajaj Finance Ltd', 'exchange': 'NSE', 'yahoo': 'BAJFINANCE.NS', 'nse': 'BAJFINANCE', 'sector': 'Finance'},
    'NESTLEIND': {'name': 'Nestle India Ltd', 'exchange': 'NSE', 'yahoo': 'NESTLEIND.NS', 'nse': 'NESTLEIND', 'sector': 'FMCG'},
    'WIPRO': {'name': 'Wipro Ltd', 'exchange': 'NSE', 'yahoo': 'WIPRO.NS', 'nse': 'WIPRO', 'sector': 'IT'},
    'HCLTECH': {'name': 'HCL Technologies Ltd', 'exchange': 'NSE', 'yahoo': 'HCLTECH.NS', 'nse': 'HCLTECH', 'sector': 'IT'},
    'ADANIENT': {'name': 'Adani Enterprises Ltd', 'exchange': 'NSE', 'yahoo': 'ADANIENT.NS', 'nse': 'ADANIENT', 'sector': 'Diversified'},
    'ONGC': {'name': 'Oil & Natural Gas Corporation Ltd', 'exchange': 'NSE', 'yahoo': 'ONGC.NS', 'nse': 'ONGC', 'sector': 'Energy'},
    'NTPC': {'name': 'NTPC Ltd', 'exchange': 'NSE', 'yahoo': 'NTPC.NS', 'nse': 'NTPC', 'sector': 'Power'},
    'POWERGRID': {'name': 'Power Grid Corporation of India Ltd', 'exchange': 'NSE', 'yahoo': 'POWERGRID.NS', 'nse': 'POWERGRID', 'sector': 'Power'},
    'JSWSTEEL': {'name': 'JSW Steel Ltd', 'exchange': 'NSE', 'yahoo': 'JSWSTEEL.NS', 'nse': 'JSWSTEEL', 'sector': 'Steel'},
    'TATAMOTORS': {'name': 'Tata Motors Ltd', 'exchange': 'NSE', 'yahoo': 'TATAMOTORS.NS', 'nse': 'TATAMOTORS', 'sector': 'Auto'},
    'TATASTEEL': {'name': 'Tata Steel Ltd', 'exchange': 'NSE', 'yahoo': 'TATASTEEL.NS', 'nse': 'TATASTEEL', 'sector': 'Steel'},
    'COALINDIA': {'name': 'Coal India Ltd', 'exchange': 'NSE', 'yahoo': 'COALINDIA.NS', 'nse': 'COALINDIA', 'sector': 'Mining'},
    'INDUSINDBK': {'name': 'IndusInd Bank Ltd', 'exchange': 'NSE', 'yahoo': 'INDUSINDBK.NS', 'nse': 'INDUSINDBK', 'sector': 'Finance'},
    'BAJAJFINSV': {'name': 'Bajaj Finserv Ltd', 'exchange': 'NSE', 'yahoo': 'BAJAJFINSV.NS', 'nse': 'BAJAJFINSV', 'sector': 'Finance'},
    'DIVISLAB': {'name': 'Divis Laboratories Ltd', 'exchange': 'NSE', 'yahoo': 'DIVISLAB.NS', 'nse': 'DIVISLAB', 'sector': 'Pharma'},
    'TECHM': {'name': 'Tech Mahindra Ltd', 'exchange': 'NSE', 'yahoo': 'TECHM.NS', 'nse': 'TECHM', 'sector': 'IT'},
    'DRREDDY': {'name': 'Dr Reddys Laboratories Ltd', 'exchange': 'NSE', 'yahoo': 'DRREDDY.NS', 'nse': 'DRREDDY', 'sector': 'Pharma'},
    'EICHERMOT': {'name': 'Eicher Motors Ltd', 'exchange': 'NSE', 'yahoo': 'EICHERMOT.NS', 'nse': 'EICHERMOT', 'sector': 'Auto'},
    'APOLLOHOSP': {'name': 'Apollo Hospitals Enterprise Ltd', 'exchange': 'NSE', 'yahoo': 'APOLLOHOSP.NS', 'nse': 'APOLLOHOSP', 'sector': 'Healthcare'},
    'BRITANNIA': {'name': 'Britannia Industries Ltd', 'exchange': 'NSE', 'yahoo': 'BRITANNIA.NS', 'nse': 'BRITANNIA', 'sector': 'FMCG'},
    'HINDALCO': {'name': 'Hindalco Industries Ltd', 'exchange': 'NSE', 'yahoo': 'HINDALCO.NS', 'nse': 'HINDALCO', 'sector': 'Metals'},
    'CIPLA': {'name': 'Cipla Ltd', 'exchange': 'NSE', 'yahoo': 'CIPLA.NS', 'nse': 'CIPLA', 'sector': 'Pharma'},
    'GRASIM': {'name': 'Grasim Industries Ltd', 'exchange': 'NSE', 'yahoo': 'GRASIM.NS', 'nse': 'GRASIM', 'sector': 'Diversified'},
    'BPCL': {'name': 'Bharat Petroleum Corporation Ltd', 'exchange': 'NSE', 'yahoo': 'BPCL.NS', 'nse': 'BPCL', 'sector': 'Energy'},
    'HEROMOTOCO': {'name': 'Hero MotoCorp Ltd', 'exchange': 'NSE', 'yahoo': 'HEROMOTOCO.NS', 'nse': 'HEROMOTOCO', 'sector': 'Auto'},
    'TATACONSUM': {'name': 'Tata Consumer Products Ltd', 'exchange': 'NSE', 'yahoo': 'TATACONSUM.NS', 'nse': 'TATACONSUM', 'sector': 'FMCG'},
    'ADANIPORTS': {'name': 'Adani Ports and Special Economic Zone Ltd', 'exchange': 'NSE', 'yahoo': 'ADANIPORTS.NS', 'nse': 'ADANIPORTS', 'sector': 'Infrastructure'},
    'SHRIRAMFIN': {'name': 'Shriram Finance Ltd', 'exchange': 'NSE', 'yahoo': 'SHRIRAMFIN.NS', 'nse': 'SHRIRAMFIN', 'sector': 'Finance'},
    'UPL': {'name': 'UPL Ltd', 'exchange': 'NSE', 'yahoo': 'UPL.NS', 'nse': 'UPL', 'sector': 'Chemicals'},
    'LTIM': {'name': 'LTIMindtree Ltd', 'exchange': 'NSE', 'yahoo': 'LTIM.NS', 'nse': 'LTIM', 'sector': 'IT'},
    'SBILIFE': {'name': 'SBI Life Insurance Company Ltd', 'exchange': 'NSE', 'yahoo': 'SBILIFE.NS', 'nse': 'SBILIFE', 'sector': 'Insurance'},
    'HDFCLIFE': {'name': 'HDFC Life Insurance Company Ltd', 'exchange': 'NSE', 'yahoo': 'HDFCLIFE.NS', 'nse': 'HDFCLIFE', 'sector': 'Insurance'},
    'ADANIGREEN': {'name': 'Adani Green Energy Ltd', 'exchange': 'NSE', 'yahoo': 'ADANIGREEN.NS', 'nse': 'ADANIGREEN', 'sector': 'Power'},
    'BANKBARODA': {'name': 'Bank of Baroda', 'exchange': 'NSE', 'yahoo': 'BANKBARODA.NS', 'nse': 'BANKBARODA', 'sector': 'Finance'},
    'PNB': {'name': 'Punjab National Bank', 'exchange': 'NSE', 'yahoo': 'PNB.NS', 'nse': 'PNB', 'sector': 'Finance'},
    'CANBK': {'name': 'Canara Bank', 'exchange': 'NSE', 'yahoo': 'CANBK.NS', 'nse': 'CANBK', 'sector': 'Finance'},
    'VEDL': {'name': 'Vedanta Ltd', 'exchange': 'NSE', 'yahoo': 'VEDL.NS', 'nse': 'VEDL', 'sector': 'Metals'},
    'INDIGO': {'name': 'InterGlobe Aviation Ltd', 'exchange': 'NSE', 'yahoo': 'INDIGO.NS', 'nse': 'INDIGO', 'sector': 'Aviation'},
    'ZOMATO': {'name': 'Zomato Ltd', 'exchange': 'NSE', 'yahoo': 'ZOMATO.NS', 'nse': 'ZOMATO', 'sector': 'Tech'},
    'PAYTM': {'name': 'One 97 Communications Ltd', 'exchange': 'NSE', 'yahoo': 'PAYTM.NS', 'nse': 'PAYTM', 'sector': 'Tech'},
    'IRCTC': {'name': 'Indian Railway Catering and Tourism Corporation Ltd', 'exchange': 'NSE', 'yahoo': 'IRCTC.NS', 'nse': 'IRCTC', 'sector': 'Services'},
    'GODREJCP': {'name': 'Godrej Consumer Products Ltd', 'exchange': 'NSE', 'yahoo': 'GODREJCP.NS', 'nse': 'GODREJCP', 'sector': 'FMCG'},
    'DABUR': {'name': 'Dabur India Ltd', 'exchange': 'NSE', 'yahoo': 'DABUR.NS', 'nse': 'DABUR', 'sector': 'FMCG'},
    'MARICO': {'name': 'Marico Ltd', 'exchange': 'NSE', 'yahoo': 'MARICO.NS', 'nse': 'MARICO', 'sector': 'FMCG'},
    'BERGEPAINT': {'name': 'Berger Paints India Ltd', 'exchange': 'NSE', 'yahoo': 'BERGEPAINT.NS', 'nse': 'BERGEPAINT', 'sector': 'Consumer'},
    'PIDILITIND': {'name': 'Pidilite Industries Ltd', 'exchange': 'NSE', 'yahoo': 'PIDILITIND.NS', 'nse': 'PIDILITIND', 'sector': 'Chemicals'},
    'TRENT': {'name': 'Trent Ltd', 'exchange': 'NSE', 'yahoo': 'TRENT.NS', 'nse': 'TRENT', 'sector': 'Retail'},
    'DMART': {'name': 'Avenue Supermarts Ltd', 'exchange': 'NSE', 'yahoo': 'DMART.NS', 'nse': 'DMART', 'sector': 'Retail'},
    'HAVELLS': {'name': 'Havells India Ltd', 'exchange': 'NSE', 'yahoo': 'HAVELLS.NS', 'nse': 'HAVELLS', 'sector': 'Consumer'},
    'DIXON': {'name': 'Dixon Technologies India Ltd', 'exchange': 'NSE', 'yahoo': 'DIXON.NS', 'nse': 'DIXON', 'sector': 'Electronics'},
    'VOLTAS': {'name': 'Voltas Ltd', 'exchange': 'NSE', 'yahoo': 'VOLTAS.NS', 'nse': 'VOLTAS', 'sector': 'Consumer'},
    'ABB': {'name': 'ABB India Ltd', 'exchange': 'NSE', 'yahoo': 'ABB.NS', 'nse': 'ABB', 'sector': 'Industrials'},
    'SIEMENS': {'name': 'Siemens Ltd', 'exchange': 'NSE', 'yahoo': 'SIEMENS.NS', 'nse': 'SIEMENS', 'sector': 'Industrials'},
    'BOSCHLTD': {'name': 'Bosch Ltd', 'exchange': 'NSE', 'yahoo': 'BOSCHLTD.NS', 'nse': 'BOSCHLTD', 'sector': 'Auto'},
    'CUMMINSIND': {'name': 'Cummins India Ltd', 'exchange': 'NSE', 'yahoo': 'CUMMINSIND.NS', 'nse': 'CUMMINSIND', 'sector': 'Industrials'},
    'DLF': {'name': 'DLF Ltd', 'exchange': 'NSE', 'yahoo': 'DLF.NS', 'nse': 'DLF', 'sector': 'RealEstate'},
    'GODREJPROP': {'name': 'Godrej Properties Ltd', 'exchange': 'NSE', 'yahoo': 'GODREJPROP.NS', 'nse': 'GODREJPROP', 'sector': 'RealEstate'},
    'OBEROIRLTY': {'name': 'Oberoi Realty Ltd', 'exchange': 'NSE', 'yahoo': 'OBEROIRLTY.NS', 'nse': 'OBEROIRLTY', 'sector': 'RealEstate'},
    'GAIL': {'name': 'GAIL India Ltd', 'exchange': 'NSE', 'yahoo': 'GAIL.NS', 'nse': 'GAIL', 'sector': 'Energy'},
    'IOC': {'name': 'Indian Oil Corporation Ltd', 'exchange': 'NSE', 'yahoo': 'IOC.NS', 'nse': 'IOC', 'sector': 'Energy'},
    'SAIL': {'name': 'Steel Authority of India Ltd', 'exchange': 'NSE', 'yahoo': 'SAIL.NS', 'nse': 'SAIL', 'sector': 'Steel'},
    'NMDC': {'name': 'NMDC Ltd', 'exchange': 'NSE', 'yahoo': 'NMDC.NS', 'nse': 'NMDC', 'sector': 'Mining'},
    'AMBUJACEM': {'name': 'Ambuja Cements Ltd', 'exchange': 'NSE', 'yahoo': 'AMBUJACEM.NS', 'nse': 'AMBUJACEM', 'sector': 'Cement'},
    'ACC': {'name': 'ACC Ltd', 'exchange': 'NSE', 'yahoo': 'ACC.NS', 'nse': 'ACC', 'sector': 'Cement'},
    'LUPIN': {'name': 'Lupin Ltd', 'exchange': 'NSE', 'yahoo': 'LUPIN.NS', 'nse': 'LUPIN', 'sector': 'Pharma'},
    'BIOCON': {'name': 'Biocon Ltd', 'exchange': 'NSE', 'yahoo': 'BIOCON.NS', 'nse': 'BIOCON', 'sector': 'Pharma'},
    'TORNTPHARM': {'name': 'Torrent Pharmaceuticals Ltd', 'exchange': 'NSE', 'yahoo': 'TORNTPHARM.NS', 'nse': 'TORNTPHARM', 'sector': 'Pharma'},
    'AUROPHARMA': {'name': 'Aurobindo Pharma Ltd', 'exchange': 'NSE', 'yahoo': 'AUROPHARMA.NS', 'nse': 'AUROPHARMA', 'sector': 'Pharma'},
    'BANDHANBNK': {'name': 'Bandhan Bank Ltd', 'exchange': 'NSE', 'yahoo': 'BANDHANBNK.NS', 'nse': 'BANDHANBNK', 'sector': 'Finance'},
    'IDFCFIRSTB': {'name': 'IDFC First Bank Ltd', 'exchange': 'NSE', 'yahoo': 'IDFCFIRSTB.NS', 'nse': 'IDFCFIRSTB', 'sector': 'Finance'},
    'FEDERALBNK': {'name': 'Federal Bank Ltd', 'exchange': 'NSE', 'yahoo': 'FEDERALBNK.NS', 'nse': 'FEDERALBNK', 'sector': 'Finance'},
    'CHOLAFIN': {'name': 'Cholamandalam Investment and Finance Company Ltd', 'exchange': 'NSE', 'yahoo': 'CHOLAFIN.NS', 'nse': 'CHOLAFIN', 'sector': 'Finance'},
    'RECLTD': {'name': 'REC Ltd', 'exchange': 'NSE', 'yahoo': 'RECLTD.NS', 'nse': 'RECLTD', 'sector': 'Finance'},
    'PFC': {'name': 'Power Finance Corporation Ltd', 'exchange': 'NSE', 'yahoo': 'PFC.NS', 'nse': 'PFC', 'sector': 'Finance'},
    'MPHASIS': {'name': 'Mphasis Ltd', 'exchange': 'NSE', 'yahoo': 'MPHASIS.NS', 'nse': 'MPHASIS', 'sector': 'IT'},
    'COFORGE': {'name': 'Coforge Ltd', 'exchange': 'NSE', 'yahoo': 'COFORGE.NS', 'nse': 'COFORGE', 'sector': 'IT'},
    'PERSISTENT': {'name': 'Persistent Systems Ltd', 'exchange': 'NSE', 'yahoo': 'PERSISTENT.NS', 'nse': 'PERSISTENT', 'sector': 'IT'},
    'OFSS': {'name': 'Oracle Financial Services Software Ltd', 'exchange': 'NSE', 'yahoo': 'OFSS.NS', 'nse': 'OFSS', 'sector': 'IT'},
}
